/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_muhaitian_jnidemo_jni_StaticJniClass */

#ifndef _Included_com_muhaitian_jnidemo_jni_StaticJniClass
#define _Included_com_muhaitian_jnidemo_jni_StaticJniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setBoolean
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setBoolean
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getChar
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setIntArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getIntArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getIntArray
  (JNIEnv *, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    setIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_setStudent
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_muhaitian_jnidemo_jni_StaticJniClass
 * Method:    getIntArray
 * Signature: ()[I
 */
JNIEXPORT jobject JNICALL Java_com_muhaitian_jnidemo_jni_StaticJniClass_getStudent
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
